name: invoice_flow
description: A multilingual invoice app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  pdf: ^3.11.0
  printing: ^5.13.2
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/NotoSansArabic-Regular.ttf